#!/usr/bin/env bash
#
# Pins the browser public facade and browser/worklet export ABI against
# accidental drift. Update browser/browser_abi.baseline only when a facade or
# export-list change is intentional and reviewed.

set -euo pipefail

readonly BASELINE="browser/browser_abi.baseline"
readonly MANIFEST="browser/moon.pkg"
readonly MBTI="browser/pkg.generated.mbti"

update_baseline=0

usage() {
  echo "Usage: $0 [--update]" >&2
}

parse_args() {
  if [[ $# -gt 1 ]]; then
    usage
    exit 2
  fi

  case "${1:-}" in
    "") ;;
    --update) update_baseline=1 ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      usage
      exit 2
      ;;
  esac
}

extract_exports() {
  local target=$1
  awk -v target="$target" '
    function brace_delta(text, opens, closes) {
      opens = gsub(/\{/, "{", text)
      closes = gsub(/\}/, "}", text)
      return opens - closes
    }
    function emit_exports(text) {
      while (match(text, /"[^"]+"/)) {
        print substr(text, RSTART + 1, RLENGTH - 2)
        found = 1
        text = substr(text, RSTART + RLENGTH)
      }
      if (text ~ /\]/) {
        exit
      }
    }
    BEGIN {
      in_target = 0
      in_exports = 0
      found = 0
      depth = 0
    }
    $0 ~ "\"" target "\"[[:space:]]*:[[:space:]]*\\{" {
      in_target = 1
      depth = brace_delta($0)
      next
    }
    in_target {
      if (in_exports) {
        emit_exports($0)
      } else if ($0 ~ /"exports"[[:space:]]*:[[:space:]]*\[/) {
        line = $0
        sub(/^.*"exports"[[:space:]]*:[[:space:]]*\[/, "", line)
        in_exports = 1
        emit_exports(line)
      }
      depth += brace_delta($0)
      if (!in_exports && depth <= 0) {
        exit 1
      }
    }
    END {
      if (!found) {
        exit 1
      }
    }
  ' "$MANIFEST"
}

write_export_section() {
  local target=$1
  echo
  echo "## $MANIFEST $target exports"
  if ! extract_exports "$target"; then
    echo "ERROR: failed to extract $target exports from $MANIFEST" >&2
    exit 1
  fi
}

write_snapshot() {
  # Regenerate public interfaces before taking the facade snapshot.
  moon info --quiet >/dev/null

  echo "# Browser facade/export ABI baseline"
  echo "# Generated by scripts/check-browser-abi.sh --update"
  echo "# Update only for reviewed changes to the browser public facade or worklet exports."
  echo
  echo "## $MBTI"
  cat "$MBTI"
  write_export_section "js"
  write_export_section "wasm-gc"
}

approved_update_message() {
  echo "If this change is intentional, review the diff, preserve browser/worklet compatibility," >&2
  echo "then run: scripts/check-browser-abi.sh --update" >&2
}

parse_args "$@"

snapshot=$(mktemp)
trap 'rm -f "$snapshot"' EXIT
write_snapshot > "$snapshot"

if [[ $update_baseline -eq 1 ]]; then
  cp "$snapshot" "$BASELINE"
  echo "Updated $BASELINE"
  exit 0
fi

if [[ ! -f "$BASELINE" ]]; then
  echo "ERROR: missing $BASELINE" >&2
  echo "Create it with: scripts/check-browser-abi.sh --update" >&2
  exit 1
fi

if ! diff -u "$BASELINE" "$snapshot"; then
  echo "" >&2
  echo "ERROR: browser facade/export ABI drift detected." >&2
  approved_update_message
  exit 1
fi

echo "OK: browser facade/export ABI matches baseline."
