#!/usr/bin/env python3
"""Parse Mini examples embedded in documentation with the production parser."""

from __future__ import annotations

import json
import os
from pathlib import Path
import subprocess
import sys
import tempfile

FENCE_MODES = {
    "```mini": "parse",
    "```mini-song": "parse_song_with_bpm",
}
DEFAULT_DOCUMENT = "docs/guides/live-coding-cookbook.md"


def extract_blocks(path: Path) -> list[tuple[int, str, str]]:
    blocks: list[tuple[int, str, str]] = []
    active: tuple[int, str] | None = None
    lines: list[str] = []

    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        marker = line.strip()
        if active is None:
            parser = FENCE_MODES.get(marker)
            if parser is not None:
                active = (line_number, parser)
                lines = []
        elif marker == "```":
            start_line, parser = active
            blocks.append((start_line, parser, "\n".join(lines)))
            active = None
            lines = []
        else:
            lines.append(line)

    if active is not None:
        start_line, _ = active
        raise ValueError(f"unterminated Mini fence at {path}:{start_line}")
    return blocks


def generated_test(document: Path, blocks: list[tuple[int, str, str]]) -> str:
    source: list[str] = [
        "// Generated by scripts/check-cookbook-mini.py; do not commit.",
        "",
    ]
    label = document.as_posix()
    for index, (line, parser, text) in enumerate(blocks):
        test_name = json.dumps(f"cookbook Mini block {index + 1} at {label}:{line}")
        input_text = json.dumps(text, ensure_ascii=False)
        failure_prefix = json.dumps(f"{label}:{line}: ")
        source.extend(
            [
                "///|",
                f"test {test_name} {{",
                f"  match {parser}({input_text}) {{",
                "    Ok(_) => ()",
                f"    Err(message) => fail({failure_prefix} + message)",
                "  }",
                "}",
                "",
            ]
        )
    return "\n".join(source)


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    if len(sys.argv) > 2:
        print(
            "usage: scripts/check-cookbook-mini.py [markdown-file]",
            file=sys.stderr,
        )
        return 2
    argument = Path(sys.argv[1] if len(sys.argv) == 2 else DEFAULT_DOCUMENT)
    document = argument if argument.is_absolute() else repo_root / argument
    if not document.is_file():
        print(f"ERROR: documentation file not found: {document}", file=sys.stderr)
        return 2
    blocks = extract_blocks(document)
    if not blocks:
        print(
            f"ERROR: no ```mini or ```mini-song blocks in {document}",
            file=sys.stderr,
        )
        return 2

    mini_dir = repo_root / "mini"
    test_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            prefix="cookbook_docs_",
            suffix="_wbtest.mbt",
            dir=mini_dir,
            delete=False,
        ) as test_file:
            test_path = Path(test_file.name)
            label = (
                document.relative_to(repo_root)
                if document.is_relative_to(repo_root)
                else document
            )
            test_file.write(generated_test(label, blocks))

        environment = os.environ.copy()
        environment.setdefault("NEW_MOON_MOD", "0")
        result = subprocess.run(
            [
                "moon",
                "test",
                str(test_path.relative_to(repo_root)),
                "--target",
                "native",
                "--deny-warn",
            ],
            cwd=repo_root,
            env=environment,
            check=False,
        )
        if result.returncode != 0:
            return result.returncode
    finally:
        if test_path is not None:
            test_path.unlink(missing_ok=True)

    pattern_count = sum(parser == "parse" for _, parser, _ in blocks)
    song_count = sum(parser == "parse_song_with_bpm" for _, parser, _ in blocks)
    print(
        f"OK: parsed {pattern_count} pattern and {song_count} song "
        "documentation blocks."
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
